<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="KAD-I-002" name="Default test" tests="9" failures="1" timestamp="17 Aug 2018 09:29:24 GMT" time="695.02" errors="0">
  <testcase name="Login" time="2.047" classname="testCases.Matrixflow"/>
  <testcase name="caseregistration" time="3.645" classname="testCases.Matrixflow"/>
  <testcase name="aasignToDE" time="5.717" classname="testCases.Matrixflow"/>
  <testcase name="dataentry" time="87.118" classname="testCases.Matrixflow"/>
  <testcase name="assigncase" time="70.016" classname="testCases.Matrixflow"/>
  <testcase name="OperationtmAssign" time="100.695" classname="testCases.Matrixflow"/>
  <testcase name="Operationtm" time="409.207" classname="testCases.Matrixflow"/>
  <testcase name="Report" time="4.912" classname="testCases.Matrixflow">
    <failure type="java.lang.Exception" message="final is :0">
      <![CDATA[java.lang.Exception: final is :0
	at pages.ReportTL.assignReport(ReportTL.java:77)
	at testCases.Matrixflow.Report(Matrixflow.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Report -->
  <testcase name="publishCase" time="0.0" classname="testCases.Matrixflow">
    <skipped/>
  </testcase> <!-- publishCase -->
</testsuite> <!-- Default test -->
