<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="9" failed="1" ignored="0" total="11" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="37747" started-at="2018-11-22T10:34:13Z" finished-at="2018-11-22T10:34:51Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="37747" started-at="2018-11-22T10:34:13Z" finished-at="2018-11-22T10:34:51Z">
      <class name="maintest.CandidateCaseRegistration">
        <test-method status="PASS" signature="beforeSuit()[pri:0, instance:maintest.CandidateCaseRegistration@1952a2d]" name="beforeSuit" is-config="true" duration-ms="125" started-at="2018-11-22T10:34:13Z" finished-at="2018-11-22T10:34:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuit -->
        <test-method status="PASS" signature="beforetest()[pri:0, instance:maintest.CandidateCaseRegistration@1952a2d]" name="beforetest" is-config="true" duration-ms="3457" started-at="2018-11-22T10:34:13Z" finished-at="2018-11-22T10:34:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforetest -->
        <test-method status="PASS" signature="setup(java.lang.reflect.Method)[pri:0, instance:maintest.CandidateCaseRegistration@1952a2d]" name="setup" is-config="true" duration-ms="21" started-at="2018-11-22T10:34:17Z" finished-at="2018-11-22T10:34:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void maintest.CandidateCaseRegistration.CandidateInitiate() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="CandidateInitiate()[pri:1, instance:maintest.CandidateCaseRegistration@1952a2d]" name="CandidateInitiate" duration-ms="4833" started-at="2018-11-22T10:34:17Z" finished-at="2018-11-22T10:34:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CandidateInitiate -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult, java.lang.reflect.Method)[pri:0, instance:maintest.CandidateCaseRegistration@1952a2d]" name="tearDown" is-config="true" duration-ms="0" started-at="2018-11-22T10:34:21Z" finished-at="2018-11-22T10:34:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=CandidateInitiate status=SUCCESS method=CandidateCaseRegistration.CandidateInitiate()[pri:1, instance:maintest.CandidateCaseRegistration@1952a2d] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void maintest.CandidateCaseRegistration.CandidateInitiate() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="CandidatedataEntry()[pri:2, instance:maintest.CandidateCaseRegistration@1952a2d]" name="CandidatedataEntry" duration-ms="26215" started-at="2018-11-22T10:34:21Z" depends-on-methods="maintest.CandidateCaseRegistration.CandidateInitiate" finished-at="2018-11-22T10:34:48Z">
          <exception class="java.lang.NoClassDefFoundError">
            <message>
              <![CDATA[candidate/Address]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NoClassDefFoundError: candidate/Address
at environment.Pages.Address(Pages.java:176)
at maintest.CandidateCaseRegistration.CandidatedataEntry(CandidateCaseRegistration.java:127)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.ClassNotFoundException: candidate.Address
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
... 27 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NoClassDefFoundError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CandidatedataEntry -->
        <test-method status="PASS" signature="setup(java.lang.reflect.Method)[pri:0, instance:maintest.CandidateCaseRegistration@1952a2d]" name="setup" is-config="true" duration-ms="0" started-at="2018-11-22T10:34:21Z" finished-at="2018-11-22T10:34:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void maintest.CandidateCaseRegistration.CandidatedataEntry() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult, java.lang.reflect.Method)[pri:0, instance:maintest.CandidateCaseRegistration@1952a2d]" name="tearDown" is-config="true" duration-ms="3166" started-at="2018-11-22T10:34:48Z" finished-at="2018-11-22T10:34:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=CandidatedataEntry status=FAILURE method=CandidateCaseRegistration.CandidatedataEntry()[pri:2, instance:maintest.CandidateCaseRegistration@1952a2d] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void maintest.CandidateCaseRegistration.CandidatedataEntry() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="SKIP" signature="VerificationSupervisor()[pri:9, instance:maintest.CandidateCaseRegistration@1952a2d]" name="VerificationSupervisor" duration-ms="0" started-at="2018-11-22T10:34:51Z" depends-on-methods="maintest.CandidateCaseRegistration.ClientSubmit" finished-at="2018-11-22T10:34:51Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method CandidateCaseRegistration.VerificationSupervisor()[pri:9, instance:maintest.CandidateCaseRegistration@1952a2d] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method CandidateCaseRegistration.VerificationSupervisor()[pri:9, instance:maintest.CandidateCaseRegistration@1952a2d] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerificationSupervisor -->
        <test-method status="SKIP" signature="Employment()[pri:5, instance:maintest.CandidateCaseRegistration@1952a2d]" name="Employment" duration-ms="0" started-at="2018-11-22T10:34:51Z" depends-on-methods="maintest.CandidateCaseRegistration.CandidatedataEntry" finished-at="2018-11-22T10:34:51Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method CandidateCaseRegistration.Employment()[pri:5, instance:maintest.CandidateCaseRegistration@1952a2d] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method CandidateCaseRegistration.Employment()[pri:5, instance:maintest.CandidateCaseRegistration@1952a2d] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Employment -->
        <test-method status="SKIP" signature="Reference()[pri:7, instance:maintest.CandidateCaseRegistration@1952a2d]" name="Reference" duration-ms="0" started-at="2018-11-22T10:34:51Z" depends-on-methods="maintest.CandidateCaseRegistration.CandidatedataEntry" finished-at="2018-11-22T10:34:51Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method CandidateCaseRegistration.Reference()[pri:7, instance:maintest.CandidateCaseRegistration@1952a2d] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method CandidateCaseRegistration.Reference()[pri:7, instance:maintest.CandidateCaseRegistration@1952a2d] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Reference -->
        <test-method status="SKIP" signature="Address()[pri:3, instance:maintest.CandidateCaseRegistration@1952a2d]" name="Address" duration-ms="0" started-at="2018-11-22T10:34:51Z" depends-on-methods="maintest.CandidateCaseRegistration.CandidatedataEntry" finished-at="2018-11-22T10:34:51Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method CandidateCaseRegistration.Address()[pri:3, instance:maintest.CandidateCaseRegistration@1952a2d] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method CandidateCaseRegistration.Address()[pri:3, instance:maintest.CandidateCaseRegistration@1952a2d] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Address -->
        <test-method status="SKIP" signature="ClientSubmit()[pri:8, instance:maintest.CandidateCaseRegistration@1952a2d]" name="ClientSubmit" duration-ms="0" started-at="2018-11-22T10:34:51Z" depends-on-methods="maintest.CandidateCaseRegistration.CandidatedataEntry" finished-at="2018-11-22T10:34:51Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method CandidateCaseRegistration.ClientSubmit()[pri:8, instance:maintest.CandidateCaseRegistration@1952a2d] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method CandidateCaseRegistration.ClientSubmit()[pri:8, instance:maintest.CandidateCaseRegistration@1952a2d] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ClientSubmit -->
        <test-method status="SKIP" signature="Education()[pri:4, instance:maintest.CandidateCaseRegistration@1952a2d]" name="Education" duration-ms="0" started-at="2018-11-22T10:34:51Z" depends-on-methods="maintest.CandidateCaseRegistration.CandidatedataEntry" finished-at="2018-11-22T10:34:51Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method CandidateCaseRegistration.Education()[pri:4, instance:maintest.CandidateCaseRegistration@1952a2d] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method CandidateCaseRegistration.Education()[pri:4, instance:maintest.CandidateCaseRegistration@1952a2d] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Education -->
        <test-method status="SKIP" signature="VoterId()[pri:6, instance:maintest.CandidateCaseRegistration@1952a2d]" name="VoterId" duration-ms="0" started-at="2018-11-22T10:34:51Z" depends-on-methods="maintest.CandidateCaseRegistration.CandidatedataEntry" finished-at="2018-11-22T10:34:51Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method CandidateCaseRegistration.VoterId()[pri:6, instance:maintest.CandidateCaseRegistration@1952a2d] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method CandidateCaseRegistration.VoterId()[pri:6, instance:maintest.CandidateCaseRegistration@1952a2d] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VoterId -->
        <test-method status="SKIP" signature="DataEntryQC()[pri:9, instance:maintest.CandidateCaseRegistration@1952a2d]" name="DataEntryQC" duration-ms="0" started-at="2018-11-22T10:34:51Z" depends-on-methods="maintest.CandidateCaseRegistration.ClientSubmit" finished-at="2018-11-22T10:34:51Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method CandidateCaseRegistration.DataEntryQC()[pri:9, instance:maintest.CandidateCaseRegistration@1952a2d] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method CandidateCaseRegistration.DataEntryQC()[pri:9, instance:maintest.CandidateCaseRegistration@1952a2d] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DataEntryQC -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:maintest.CandidateCaseRegistration@1952a2d]" name="teardown" is-config="true" duration-ms="0" started-at="2018-11-22T10:34:51Z" finished-at="2018-11-22T10:34:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="SKIP" signature="VerificationIntiation()[pri:10, instance:maintest.CandidateCaseRegistration@1952a2d]" name="VerificationIntiation" duration-ms="0" started-at="2018-11-22T10:34:51Z" depends-on-methods="maintest.CandidateCaseRegistration.VerificationSupervisor" finished-at="2018-11-22T10:34:51Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method CandidateCaseRegistration.VerificationIntiation()[pri:10, instance:maintest.CandidateCaseRegistration@1952a2d] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method CandidateCaseRegistration.VerificationIntiation()[pri:10, instance:maintest.CandidateCaseRegistration@1952a2d] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerificationIntiation -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:maintest.CandidateCaseRegistration@1952a2d]" name="afterSuite" is-config="true" duration-ms="267" started-at="2018-11-22T10:34:51Z" finished-at="2018-11-22T10:34:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- maintest.CandidateCaseRegistration -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
