<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="8032" started-at="2018-06-22T12:26:39Z" finished-at="2018-06-22T12:26:47Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="8032" started-at="2018-06-22T12:26:39Z" finished-at="2018-06-22T12:26:47Z">
      <class name="testCases.ExtentReportDemo2">
        <test-method status="PASS" signature="beforeSuit()[pri:0, instance:testCases.ExtentReportDemo2@1ee9faa]" name="beforeSuit" is-config="true" duration-ms="269" started-at="2018-06-22T17:56:39Z" finished-at="2018-06-22T17:56:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuit -->
        <test-method status="FAIL" signature="loginTest()[pri:0, instance:testCases.ExtentReportDemo2@1ee9faa]" name="loginTest" duration-ms="7670" started-at="2018-06-22T17:56:39Z" finished-at="2018-06-22T17:56:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at testCases.ExtentReportDemo2.loginTest(ExtentReportDemo2.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="setup(java.lang.reflect.Method)[pri:0, instance:testCases.ExtentReportDemo2@1ee9faa]" name="setup" is-config="true" duration-ms="0" started-at="2018-06-22T17:56:39Z" finished-at="2018-06-22T17:56:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testCases.ExtentReportDemo2.loginTest() throws java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult, java.lang.reflect.Method)[pri:0, instance:testCases.ExtentReportDemo2@1ee9faa]" name="tearDown" is-config="true" duration-ms="328" started-at="2018-06-22T17:56:47Z" finished-at="2018-06-22T17:56:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginTest status=FAILURE method=ExtentReportDemo2.loginTest()[pri:0, instance:testCases.ExtentReportDemo2@1ee9faa] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void testCases.ExtentReportDemo2.loginTest() throws java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="SKIP" signature="testTwo()[pri:0, instance:testCases.ExtentReportDemo2@1ee9faa]" name="testTwo" duration-ms="16" started-at="2018-06-22T17:56:47Z" depends-on-methods="testCases.ExtentReportDemo2.loginTest" finished-at="2018-06-22T17:56:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTwo -->
        <test-method status="SKIP" signature="testThree()[pri:0, instance:testCases.ExtentReportDemo2@1ee9faa]" name="testThree" duration-ms="0" started-at="2018-06-22T17:56:47Z" depends-on-methods="testCases.ExtentReportDemo2.testTwo" finished-at="2018-06-22T17:56:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testThree -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:testCases.ExtentReportDemo2@1ee9faa]" name="afterSuite" is-config="true" duration-ms="883" started-at="2018-06-22T17:56:47Z" finished-at="2018-06-22T17:56:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- testCases.ExtentReportDemo2 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
